[[linter]]
code = 'FLAKE8'
include_patterns = ['**/*.py']
exclude_patterns = [
    '.git/**',
    'benchmarks/**',
    'docs/**',
    'examples/**',
    'notebooks/**',
]
command = [
    'python3',
    'tools/lint/flake8_linter.py',
    '--',
    '@{{PATHSFILE}}'
]
init_command = [
    'python3',
    'tools/lint/pip_init.py',
    '--dry-run={{DRYRUN}}',
    'flake8==3.8.2',
    'flake8-bugbear==20.1.4',
    'flake8-comprehensions==3.3.0',
    'flake8-executable==2.0.4',
    'flake8-pyi==20.5.0',
    'mccabe==0.6.1',
    'pycodestyle==2.6.0',
    'pyflakes==2.2.0',
]

[[linter]]
code = 'NEWLINE'
include_patterns=['**']
exclude_patterns=[]
command = [
    'python3',
    'tools/lints/newlines_linter.py',
    '--',
    '@{{PATHSFILE}}',
]
is_formatter = true

[[linter]]
code = 'SPACES'
include_patterns = ['**']
exclude_patterns = []
command = [
    'python3',
    'tools/lint/grep_linter.py',
    '--pattern=[[:blank:]]$',
    '--linter-name=SPACES',
    '--error-name=trailing spaces',
    '--replace-pattern=s/[[:blank:]]+$//',
    """--error-description=\
        This line has trailing spaces; please remove them.\
    """,
    '--',
    '@{{PATHSFILE}}'
]

[[linter]]
code = 'TABS'
include_patterns = ['**']
exclude_patterns = [
    '**/*.svg',
    '**/*Makefile',
    '**/.gitattributes',
    '**/.gitmodules',
    '.lintrunner.toml',
]
command = [
    'python3',
    'tools/lint/grep_linter.py',
    # @lint-ignore TXT2
    '--pattern= ',
    '--linter-name=TABS',
    '--error-name=saw some tabs',
    '--replace-pattern=s/\t/    /',
    """--error-description=\
        This line has tabs; please replace them with spaces.\
    """,
    '--',
    '@{{PATHSFILE}}'
]

# [[linter]]
# code = 'BLACK'
# include_patterns = [
#     '**/*.py',
# ]
# command = [
#     'python3',
#     'tools/lint/black_linter.py',
#     '--',
#     '@{{PATHSFILE}}'
# ]
# init_command = [
#     'python3',
#     'tools/lint/pip_init.py',
#     '--dry-run={{DRYRUN}}',
#     'black==22.3.0',
# ]
# is_formatter = true
